version: '2'
services:
  myhero-ernst:
    build: .
    image: juliocisco/myhero-ernst
    ports:
     - "15000:5000"
    environment:
     - myhero_data_key=${MYHERO_DATA_KEY}
     - myhero_data_server=http://myhero-data:5000
     - myhero_mqtt_host=myhero-mosca
     - myhero_mqtt_port=1883
     - myhero_data_server=http://myhero-data:5000
networks:
  default:
     external:
       name: myherodata_default
